sudo: required
dist: trusty
language: node_js
before_install:
  - curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update
  - sudo apt-get install yarn
  - npm install -g gulp-cli webdriver-manager pm2
install:
  - yarn install
before_script:
  - webdriver-manager update
  - pm2 start webdriver-manager -- start
  # tmp debugging
  - pm2 show webdriver-manager
  - cat $HOME/.pm2/logs/webdriver-manager*.log
script:
  - gulp unit-test
  - gulp functional-test
after_success:
  # merge coverage
  - gulp coverage
  # upload results to sonarcloud.io
  - gulp sonar
  # upload results to coveralls
  - gulp coveralls
after_script:
  - pm2 delete webdriver-manager
node_js:
  - '8'
addons:
  chrome: stable
cache:
  directories:
    - "node_modules"
